// 
// Decompiled by Procyon v0.5.34
// 

package com.applovin.impl.sdk;

import java.util.Collections;
import java.util.Collection;
import com.applovin.impl.a.q;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

class ea
{
    public static final ec<String> A;
    public static final ec<String> B;
    public static final ec<Boolean> C;
    public static final ec<Long> D;
    public static final ec<Boolean> E;
    public static final ec<Long> F;
    public static final ec<Boolean> G;
    public static final ec<Long> H;
    public static final ec<String> I;
    public static final ec<Boolean> J;
    public static final ec<Boolean> K;
    public static final ec<Boolean> L;
    public static final ec<String> M;
    public static final ec<String> N;
    public static final ec<String> O;
    public static final ec<Boolean> P;
    public static final ec<Boolean> Q;
    public static final ec<Boolean> R;
    public static final ec<Boolean> S;
    public static final ec<Integer> T;
    public static final ec<Boolean> U;
    public static final ec<String> V;
    public static final ec<String> W;
    public static final ec<String> X;
    public static final ec<String> Y;
    public static final ec<String> Z;
    public static final ec<Boolean> a;
    public static final ec<Integer> aA;
    public static final ec<Integer> aB;
    public static final ec<Integer> aC;
    public static final ec<Integer> aD;
    public static final ec<Integer> aE;
    public static final ec<Integer> aF;
    public static final ec<Integer> aG;
    public static final ec<Integer> aH;
    public static final ec<Integer> aI;
    public static final ec<Integer> aJ;
    public static final ec<Integer> aK;
    public static final ec<Integer> aL;
    public static final ec<Integer> aM;
    public static final ec<Integer> aN;
    public static final ec<Integer> aO;
    public static final ec<Boolean> aP;
    public static final ec<String> aQ;
    public static final ec<Integer> aR;
    public static final ec<Integer> aS;
    public static final ec<Integer> aT;
    public static final ec<Boolean> aU;
    public static final ec<Boolean> aV;
    public static final ec<Integer> aW;
    public static final ec<Boolean> aX;
    public static final ec<Boolean> aY;
    public static final ec<Long> aZ;
    public static final ec<String> aa;
    public static final ec<String> ab;
    public static final ec<String> ac;
    public static final ec<String> ad;
    public static final ec<String> ae;
    public static final ec<Boolean> af;
    public static final ec<String> ag;
    public static final ec<String> ah;
    public static final ec<String> ai;
    public static final ec<String> aj;
    public static final ec<Boolean> ak;
    public static final ec<String> al;
    public static final ec<String> am;
    public static final ec<String> an;
    public static final ec<String> ao;
    public static final ec<Boolean> ap;
    public static final ec<Boolean> aq;
    public static final ec<Integer> ar;
    public static final ec<Integer> as;
    public static final ec<Integer> at;
    public static final ec<Integer> au;
    public static final ec<Integer> av;
    public static final ec<Integer> aw;
    public static final ec<Integer> ax;
    public static final ec<Integer> ay;
    public static final ec<Integer> az;
    public static final ec<Boolean> b;
    public static final ec<Boolean> bA;
    public static final ec<Boolean> bB;
    public static final ec<Boolean> bC;
    public static final ec<Boolean> bD;
    public static final ec<Integer> bE;
    public static final ec<Boolean> bF;
    public static final ec<Boolean> bG;
    public static final ec<Integer> bH;
    public static final ec<Integer> bI;
    public static final ec<Integer> bJ;
    public static final ec<Boolean> bK;
    public static final ec<Boolean> bL;
    public static final ec<Boolean> bM;
    public static final ec<Boolean> bN;
    public static final ec<Boolean> bO;
    public static final ec<Boolean> bP;
    public static final ec<String> bQ;
    public static final ec<Boolean> bR;
    public static final ec<Boolean> bS;
    public static final ec<Integer> bT;
    public static final ec<Integer> bU;
    public static final ec<Boolean> bV;
    public static final ec<String> bW;
    public static final ec<Integer> bX;
    public static final ec<Integer> bY;
    public static final ec<Integer> bZ;
    public static final ec<Integer> ba;
    public static final ec<Boolean> bb;
    public static final ec<Boolean> bc;
    public static final ec<Boolean> bd;
    public static final ec<Boolean> be;
    public static final ec<Boolean> bf;
    public static final ec<Boolean> bg;
    public static final ec<Boolean> bh;
    public static final ec<Boolean> bi;
    public static final ec<Boolean> bj;
    public static final ec<Boolean> bk;
    public static final ec<Boolean> bl;
    public static final ec<Integer> bm;
    public static final ec<Integer> bn;
    public static final ec<Integer> bo;
    public static final ec<Boolean> bp;
    public static final ec<Integer> bq;
    public static final ec<Integer> br;
    public static final ec<Integer> bs;
    public static final ec<Boolean> bt;
    public static final ec<Boolean> bu;
    public static final ec<Boolean> bv;
    public static final ec<Boolean> bw;
    public static final ec<Integer> bx;
    public static final ec<Integer> by;
    public static final ec<Integer> bz;
    public static final ec<Boolean> c;
    public static final ec<Boolean> cA;
    public static final ec<String> cB;
    public static final ec<Boolean> cC;
    public static final ec<Long> cD;
    public static final ec<Long> cE;
    public static final ec<Boolean> cF;
    public static final ec<Boolean> cG;
    public static final ec<Boolean> cH;
    public static final ec<Long> cI;
    public static final ec<Integer> cJ;
    public static final ec<Integer> cK;
    public static final ec<Integer> cL;
    public static final ec<Boolean> cM;
    public static final ec<Integer> cN;
    public static final ec<Long> cO;
    public static final ec<Integer> cP;
    public static final ec<Integer> cQ;
    public static final ec<Boolean> cR;
    public static final ec<Boolean> cS;
    public static final ec<Boolean> cT;
    public static final ec<String> cU;
    public static final ec<Boolean> cV;
    public static final ec<Boolean> cW;
    public static final ec<Boolean> cX;
    public static final ec<Boolean> cY;
    public static final ec<Boolean> cZ;
    public static final ec<Integer> ca;
    public static final ec<Integer> cb;
    public static final ec<Boolean> cc;
    public static final ec<Boolean> cd;
    public static final ec<Boolean> ce;
    public static final ec<Boolean> cf;
    public static final ec<String> cg;
    public static final ec<Boolean> ch;
    public static final ec<Boolean> ci;
    public static final ec<Boolean> cj;
    public static final ec<Boolean> ck;
    public static final ec<Boolean> cl;
    public static final ec<String> cm;
    public static final ec<Boolean> cn;
    public static final ec<Boolean> co;
    public static final ec<Boolean> cp;
    public static final ec<String> cq;
    public static final ec<String> cr;
    public static final ec<String> cs;
    public static final ec<String> ct;
    public static final ec<Long> cu;
    public static final ec<Float> cv;
    public static final ec<Boolean> cw;
    public static final ec<Boolean> cx;
    public static final ec<Boolean> cy;
    public static final ec<Long> cz;
    public static final ec<Boolean> d;
    public static final ec<Boolean> dA;
    public static final ec<Integer> dB;
    public static final ec<Boolean> dC;
    public static final ec<Boolean> dD;
    public static final ec<Boolean> dE;
    public static final ec<Boolean> dF;
    public static final ec<Boolean> dG;
    public static final ec<Boolean> dH;
    public static final ec<Integer> dI;
    public static final ec<Integer> dJ;
    public static final ec<Integer> dK;
    private static final List<?> dL;
    private static final List<ec<?>> dM;
    public static final ec<Boolean> da;
    public static final ec<Boolean> db;
    public static final ec<Boolean> dc;
    public static final ec<Boolean> dd;
    public static final ec<Boolean> de;
    public static final ec<Integer> df;
    public static final ec<Boolean> dg;
    public static final ec<Boolean> dh;
    public static final ec<Integer> di;
    public static final ec<Integer> dj;
    public static final ec<Integer> dk;
    public static final ec<Boolean> dl;
    public static final ec<Boolean> dm;
    public static final ec<Long> dn;
    public static final ec<Long> do;
    public static final ec<Boolean> dp;
    public static final ec<Integer> dq;
    public static final ec<Integer> dr;
    public static final ec<Integer> ds;
    public static final ec<Integer> dt;
    public static final ec<Integer> du;
    public static final ec<String> dv;
    public static final ec<String> dw;
    public static final ec<Long> dx;
    public static final ec<String> dy;
    public static final ec<String> dz;
    public static final ec<Boolean> e;
    public static final ec<String> f;
    public static final ec<String> g;
    public static final ec<String> h;
    public static final ec<Integer> i;
    public static final ec<Integer> j;
    public static final ec<Integer> k;
    public static final ec<Boolean> l;
    public static final ec<String> m;
    public static final ec<String> n;
    public static final ec<String> o;
    public static final ec<String> p;
    public static final ec<String> q;
    public static final ec<String> r;
    public static final ec<String> s;
    public static final ec<Long> t;
    public static final ec<String> u;
    public static final ec<Integer> v;
    public static final ec<Integer> w;
    public static final ec<Integer> x;
    public static final ec<Integer> y;
    public static final ec<Integer> z;
    
    static {
        dL = Arrays.asList(Boolean.class, Float.class, Integer.class, Long.class, String.class);
        dM = new ArrayList<ec<?>>();
        a = a("is_disabled", false);
        b = a("honor_publisher_settings", true);
        c = a("honor_publisher_settings_verbose_logging", true);
        d = a("honor_publisher_settings_auto_preload_ad_sizes", true);
        e = a("honor_publisher_settings_auto_preload_ad_types", true);
        f = a("device_id", "");
        g = a("publisher_id", "");
        h = a("device_token", "");
        i = a("submit_data_retry_count_v1", 1);
        j = a("vr_retry_count_v1", 1);
        k = a("fetch_ad_retry_count_v1", 1);
        l = a("is_verbose_logging", false);
        m = a("api_endpoint", "https://d.applovin.com/");
        n = a("adserver_endpoint", "https://a.applovin.com/");
        o = a("mediation_tracking_endpoint", "https://rt.applovin.com/med");
        p = a("event_tracking_endpoint", "https://rt.applovin.com/pix");
        q = a("api_backup_endpoint", "https://d.applvn.com/");
        r = a("adserver_backup_endpoint", "https://a.applvn.com/");
        s = a("event_tracking_backup_endpoint", "https://rt.applvn.com/pix");
        t = a("get_retry_delay_v1", 10000L);
        u = a("hash_algorithm", "SHA-1");
        v = a("short_hash_size", 16);
        w = a("http_connection_timeout", 30000);
        x = a("fetch_ad_connection_timeout", 30000);
        y = a("http_socket_timeout", 20000);
        z = a("ad_session_minutes", 60);
        A = a("sc", "");
        B = a("ad_request_parameters", "");
        C = a("ad_refresh_enabled", true);
        D = a("ad_refresh_seconds", 120L);
        E = a("mrec_ad_refresh_enabled", true);
        F = a("mrec_ad_refresh_seconds", 120L);
        G = a("leader_ad_refresh_enabled", true);
        H = a("leader_ad_refresh_seconds", 120L);
        I = a("plugin_version", "");
        J = a("ad_preload_enabled", true);
        K = a("ad_resource_caching_enabled", true);
        L = a("fail_ad_load_on_failed_video_cache", true);
        M = a("resource_cache_prefix", "https://vid.applovin.com/,https://pdn.applovin.com/,https://img.applovin.com/,https://d.applovin.com/,https://assets.applovin.com/,https://cdnjs.cloudflare.com/,http://vid.applovin.com/,http://pdn.applovin.com/,http://img.applovin.com/,http://d.applovin.com/,http://assets.applovin.com/,http://cdnjs.cloudflare.com/");
        N = a("ad_auto_preload_sizes", "");
        O = a("ad_auto_preload_msizes", "");
        P = a("ad_auto_preload_incent", true);
        Q = a("ad_auto_preload_mincent", true);
        R = a("is_track_ad_info", true);
        S = a("force_back_button_enabled_always", false);
        T = a("close_fade_in_time", 400);
        U = a("show_close_on_exit", true);
        V = a("text_incent_prompt_title", "Earn a Reward");
        W = a("text_incent_prompt_body", "Would you like to watch a video for a reward?");
        X = a("text_incent_prompt_yes_option", "Watch Now");
        Y = a("text_incent_prompt_no_option", "No Thanks");
        Z = a("text_incent_completion_title", "Video Reward");
        aa = a("text_incent_completion_body_success", "You have earned a reward!");
        ab = a("text_incent_completion_body_quota_exceeded", "You have already earned the maximum reward for today.");
        ac = a("text_incent_completion_body_reward_rejected", "Your reward was rejected.");
        ad = a("text_incent_completion_body_network_failure", "We were unable to contact the rewards server. Please try again later.");
        ae = a("text_incent_completion_close_option", "Okay");
        af = a("incent_warning_enabled", false);
        ag = a("text_incent_warning_title", "Attention!");
        ah = a("text_incent_warning_body", "You won\u2019t get your reward if the video hasn\u2019t finished.");
        ai = a("text_incent_warning_close_option", "Close");
        aj = a("text_incent_warning_continue_option", "Keep Watching");
        ak = a("incent_nonvideo_warning_enabled", false);
        al = a("text_incent_nonvideo_warning_title", "Attention!");
        am = a("text_incent_nonvideo_warning_body", "You won\u2019t get your reward if the game hasn\u2019t finished.");
        an = a("text_incent_nonvideo_warning_close_option", "Close");
        ao = a("text_incent_nonvideo_warning_continue_option", "Keep Playing");
        ap = a("show_incent_prepopup", true);
        aq = a("show_incent_postpopup", true);
        ar = a("preload_capacity_banner_regular_direct", 0);
        as = a("preload_capacity_banner_regular_indirect", 0);
        at = a("preload_capacity_mrec_regular_direct", 0);
        au = a("preload_capacity_mrec_regular_indirect", 0);
        av = a("preload_capacity_leader_regular_direct", 0);
        aw = a("preload_capacity_leader_regular_indirect", 0);
        ax = a("preload_capacity_inter_regular_direct", 0);
        ay = a("preload_capacity_inter_regular_indirect", 0);
        az = a("preload_capacity_inter_videoa_direct", 0);
        aA = a("preload_capacity_inter_videoa_indirect", 0);
        aB = a("extended_preload_capacity_banner_regular_direct", 15);
        aC = a("extended_preload_capacity_banner_regular_indirect", 15);
        aD = a("extended_preload_capacity_mrec_regular_direct", 15);
        aE = a("extended_preload_capacity_mrec_regular_indirect", 15);
        aF = a("extended_preload_capacity_leader_regular_direct", 15);
        aG = a("extended_preload_capacity_leader_regular_indirect", 15);
        aH = a("extended_preload_capacity_inter_regular_direct", 15);
        aI = a("extended_preload_capacity_inter_regular_indirect", 15);
        aJ = a("extended_preload_capacity_inter_videoa_direct", 15);
        aK = a("extended_preload_capacity_inter_videoa_indirect", 15);
        aL = a("preload_capacity_zone", 1);
        aM = a("preload_capacity_zone_native", 1);
        aN = a("extended_preload_capacity_zone", 15);
        aO = a("preload_capacity_native_native_direct", 0);
        aP = a("dismiss_video_on_error", true);
        aQ = a("precache_delimiters", ")]',");
        aR = a("close_button_size_video", 30);
        aS = a("close_button_top_margin_video", 8);
        aT = a("close_button_right_margin_video", 4);
        aU = a("force_back_button_enabled_poststitial", false);
        aV = a("force_back_button_enabled_close_button", false);
        aW = a("close_button_touch_area", 0);
        aX = a("is_video_skippable", false);
        aY = a("cache_cleanup_enabled", false);
        aZ = a("cache_file_ttl_seconds", 86400L);
        ba = a("cache_max_size_mb", -1);
        bb = a("preload_merge_init_tasks_inter_regular_direct", false);
        bc = a("preload_merge_init_tasks_inter_videoa_direct", false);
        bd = a("preload_merge_init_tasks_banner_regular_direct", false);
        be = a("preload_merge_init_tasks_mrec_regular_direct", false);
        bf = a("preload_merge_init_tasks_leader_regular_direct", false);
        bg = a("preload_merge_init_tasks_inter_regular_indirect", false);
        bh = a("preload_merge_init_tasks_inter_videoa_indirect", false);
        bi = a("preload_merge_init_tasks_banner_regular_indirect", false);
        bj = a("preload_merge_init_tasks_mrec_regular_indirect", false);
        bk = a("preload_merge_init_tasks_leader_regular_indirect", false);
        bl = a("preload_merge_init_tasks_zones", false);
        bm = a("submit_postback_timeout", 10000);
        bn = a("submit_postback_retries", 4);
        bo = a("widget_imp_tracking_delay", 2000);
        bp = a("draw_countdown_clock", true);
        bq = a("countdown_clock_size", 32);
        br = a("countdown_clock_stroke_size", 4);
        bs = a("countdown_clock_text_size", 28);
        bt = a("ad_auto_preload_native", false);
        bu = a("preload_native_ad_on_dequeue", false);
        bv = a("widget_fail_on_slot_count_diff", true);
        bw = a("video_zero_length_as_computed", false);
        bx = a("video_countdown_clock_margin", 10);
        by = a("video_countdown_clock_gravity", 83);
        bz = a("widget_latch_timeout_ms", 500);
        bA = a("android_gc_on_widget_detach", true);
        bB = a("lhs_close_button_video", false);
        bC = a("lhs_skip_button", true);
        bD = a("countdown_toggleable", false);
        bE = a("native_batch_precache_count", 1);
        bF = a("mute_controls_enabled", false);
        bG = a("allow_user_muting", true);
        bH = a("mute_button_size", 32);
        bI = a("mute_button_margin", 10);
        bJ = a("mute_button_gravity", 85);
        bK = a("qq", false);
        bL = a("qq1", true);
        bM = a("hw_accelerate_webviews", false);
        bN = a("mute_videos", false);
        bO = a("show_mute_by_default", false);
        bP = a("mute_with_user_settings", true);
        bQ = a("top_level_events", "landing,paused,resumed,checkout,iap");
        bR = a("events_enabled", true);
        bS = a("force_ssl", false);
        bT = a("postback_service_max_queue_size", 100);
        bU = a("max_postback_attempts", 3);
        bV = a("click_overlay_enabled", false);
        bW = a("click_overlay_color", "#66000000");
        bX = a("click_tracking_retry_count_v1", 3);
        bY = a("click_tracking_retry_delay", 2000);
        bZ = a("click_tracking_timeout", 10000);
        ca = a("android_click_spinner_size", 50);
        cb = a("android_click_spinner_style", 16973853);
        cc = a("android_require_external_storage_permission", true);
        cd = a("android_drop_nomedia", true);
        ce = a("native_auto_cache_preload_resources", true);
        cf = a("video_immersive_mode_enabled", false);
        cg = a("fireos_manufacturer_list", "amazon");
        ch = a("fireos_collect_google_idfa_on_fail", false);
        ci = a("fireos_hide_adview_on_init", true);
        cj = a("fireos_load_empty_adview_on_init", false);
        ck = a("sanitize_webview", false);
        cl = a("force_rerender", false);
        cm = a("webview_package_name", "com.google.android.webview");
        cn = a("check_webview_has_gesture", false);
        co = a("adr", false);
        cp = a("hgn", false);
        cq = a("emulator_hardware_list", "ranchu,goldfish,vbox");
        cr = a("emulator_device_list", "generic,vbox");
        cs = a("emulator_manufacturer_list", "Genymotion");
        ct = a("emulator_model_list", "Android SDK built for x86");
        cu = a("inter_display_delay", 200L);
        cv = a("volume_normalization_factor", 6.6666665f);
        cw = a("lock_specific_orientation", false);
        cx = a("video_callbacks_for_incent_nonvideo_ads_enabled", true);
        cy = a("user_agent_collection_enabled", false);
        cz = a("user_agent_collection_timeout_ms", 600L);
        cA = a("handle_window_actions", false);
        cB = a("soft_buttons_resource_id", "config_showNavigationBar");
        cC = a("immediate_render", false);
        cD = a("video_resume_delay", 250L);
        cE = a("force_hide_status_bar_delay_ms", 0L);
        cF = a("load_ads_if_no_internet", true);
        cG = a("display_ads_if_no_internet", true);
        cH = a("network_available_if_none_detected", true);
        cI = a("expandable_close_button_animation_duration_ms", 300L);
        cJ = a("expandable_close_button_size", 27);
        cK = a("expandable_h_close_button_margin", 10);
        cL = a("expandable_t_close_button_margin", 10);
        cM = a("expandable_lhs_close_button", false);
        cN = a("expandable_close_button_touch_area", 0);
        cO = a("progress_bar_step", 25L);
        cP = a("progress_bar_scale", 10000);
        cQ = a("progress_bar_vertical_padding", -8);
        cR = a("click_failed_expand", false);
        cS = a("ignore_is_showing", false);
        cT = a("wrapped_zones", false);
        cU = a("wrapped_sizes", "");
        cV = a("return_wrapped_ad_on_empty_queue", false);
        cW = a("consider_wrapped_ad_preloaded", false);
        cX = a("preload_persisted_zones", true);
        cY = a("persist_zones", true);
        cZ = a("validate_zone_input", false);
        da = a("cleanup_webview", false);
        db = a("dismiss_expanded_adview_on_refresh", false);
        dc = a("dismiss_expanded_adview_on_detach", false);
        dd = a("detach_update_listener_on_pause", false);
        de = a("contract_on_close_ad_command", false);
        df = a("response_buffer_size", 16000);
        dg = a("sp_apply", true);
        dh = a("sr_0", true);
        di = a("fetch_basic_settings_connection_timeout_ms", 5000);
        dj = a("fetch_basic_settings_retry_count", 3);
        dk = a("fetch_basic_settings_retry_delay_ms", 2000);
        dl = a("session_tracking_enabled", false);
        dm = a("session_tracking_cooldown_on_event_fire", true);
        dn = a("session_tracking_resumed_cooldown_minutes", 90L);
        do = a("session_tracking_paused_cooldown_minutes", 90L);
        dp = a("track_app_paused", false);
        dq = a("vast_max_wrapper_depth", 5);
        dr = a("vast_wrapper_resolution_retry_count_v1", 1);
        ds = a("vast_wrapper_resolution_connection_timeout", 30000);
        dt = a("vast_max_response_length", 640000);
        du = a("vast_video_selection_policy", com.applovin.impl.a.q.c.ordinal());
        dv = a("vast_image_html", "<html><head><style>html,body{height:100%;width:100%}body{background-image:url({SOURCE});background-repeat:no-repeat;background-size:contain;background-position:center;}a{position:absolute;top:0;bottom:0;left:0;right:0}</style></head><body><a href=\"applovin://com.applovin.sdk/adservice/track_click_now\"></a></body></html>");
        dw = a("vast_link_html", "<html><head><style>html,body,iframe{height:100%;width:100%;}body{margin:0}iframe{border:0;overflow:hidden;position:absolute}</style></head><body><iframe src={SOURCE} frameborder=0></iframe></body></html>");
        dx = a("vast_progress_tracking_countdown_step", 1000L);
        dy = a("vast_unsupported_video_types", "video/ogg,video/x-flv");
        dz = a("vast_unsupported_video_extensions", "ogv,flv");
        dA = a("vast_validate_with_extension_if_no_video_type", true);
        dB = a("num_ads_preload_ahead", 2);
        dC = a("mediation_load_last_session_adapters_on_next_init", true);
        dD = a("mediation_load_predefined_adapters_on_next_init", true);
        dE = a("mediation_track_imp", true);
        dF = a("mediation_track_clk", true);
        dG = a("mediation_track_err", true);
        dH = a("submit_ad_stats_enabled", false);
        dI = a("submit_ad_stats_connection_timeout", 30000);
        dJ = a("submit_ad_stats_retry_count", 1);
        dK = a("submit_ad_stats_max_count", 500);
    }
    
    private static <T> ec<T> a(final String s, final T t) {
        if (t == null) {
            throw new IllegalArgumentException("No default value specified");
        }
        if (!ea.dL.contains(t.getClass())) {
            throw new IllegalArgumentException("Unsupported value type: " + t.getClass());
        }
        final ec<Object> ec = new ec<Object>(s, t, null);
        ea.dM.add(ec);
        return (ec<T>)ec;
    }
    
    public static Collection<ec<?>> a() {
        return (Collection<ec<?>>)Collections.unmodifiableList((List<?>)ea.dM);
    }
    
    public static int b() {
        return ea.dM.size();
    }
}
