package com.google.android.gms.games.internal.player;

import android.text.TextUtils;

public final class zze {
    public final String name;
    public final String zzcc;
    public final String zzch;
    public final String zzll;
    public final String zzlm;
    public final String zzln;
    public final String zzlo;
    public final String zzlp;
    public final String zzlq;
    public final String zzlr;
    public final String zzls;
    public final String zzlt;
    public final String zzlu;
    public final String zzlv;
    public final String zzlw;
    public final String zzlx;
    public final String zzly;
    public final String zzlz;
    public final String zzma;
    private final String zzmb;
    public final String zzmc;
    public final String zzmd;
    public final String zzme;
    public final String zzmf;
    public final String zzmg;
    public final String zzmh;
    public final String zzmi;
    public final String zzmj;
    public final String zzmk;
    public final String zzml;
    public final String zzmm;
    public final String zzmn;
    public final String zzmo;
    public final String zzmp;
    public final String zzmq;

    public zze(String str) {
        String str2;
        if (TextUtils.isEmpty(str)) {
            this.zzll = "external_player_id";
            this.zzlm = "profile_name";
            this.zzln = "profile_icon_image_uri";
            this.zzlo = "profile_icon_image_url";
            this.zzlp = "profile_hi_res_image_uri";
            this.zzlq = "profile_hi_res_image_url";
            this.zzlr = "last_updated";
            this.zzls = "is_in_circles";
            this.zzlt = "played_with_timestamp";
            this.zzlu = "current_xp_total";
            this.zzlv = "current_level";
            this.zzlw = "current_level_min_xp";
            this.zzlx = "current_level_max_xp";
            this.zzly = "next_level";
            this.zzlz = "next_level_max_xp";
            this.zzma = "last_level_up_timestamp";
            this.zzcc = "player_title";
            this.zzmb = "has_all_public_acls";
            this.zzmc = "is_profile_visible";
            this.zzmd = "most_recent_external_game_id";
            this.zzme = "most_recent_game_name";
            this.zzmf = "most_recent_activity_timestamp";
            this.zzmg = "most_recent_game_icon_uri";
            this.zzmh = "most_recent_game_hi_res_uri";
            this.zzmi = "most_recent_game_featured_uri";
            this.zzmj = "has_debug_access";
            this.zzch = "gamer_tag";
            this.name = "real_name";
            this.zzmk = "banner_image_landscape_uri";
            this.zzml = "banner_image_landscape_url";
            this.zzmm = "banner_image_portrait_uri";
            this.zzmn = "banner_image_portrait_url";
            this.zzmo = "gamer_friend_status";
            this.zzmp = "gamer_friend_update_timestamp";
            str2 = "is_muted";
        } else {
            String valueOf = String.valueOf(str);
            str2 = String.valueOf("external_player_id");
            this.zzll = str2.length() != 0 ? valueOf.concat(str2) : new String(valueOf);
            valueOf = String.valueOf(str);
            str2 = String.valueOf("profile_name");
            this.zzlm = str2.length() != 0 ? valueOf.concat(str2) : new String(valueOf);
            valueOf = String.valueOf(str);
            str2 = String.valueOf("profile_icon_image_uri");
            this.zzln = str2.length() != 0 ? valueOf.concat(str2) : new String(valueOf);
            valueOf = String.valueOf(str);
            str2 = String.valueOf("profile_icon_image_url");
            this.zzlo = str2.length() != 0 ? valueOf.concat(str2) : new String(valueOf);
            valueOf = String.valueOf(str);
            str2 = String.valueOf("profile_hi_res_image_uri");
            this.zzlp = str2.length() != 0 ? valueOf.concat(str2) : new String(valueOf);
            valueOf = String.valueOf(str);
            str2 = String.valueOf("profile_hi_res_image_url");
            this.zzlq = str2.length() != 0 ? valueOf.concat(str2) : new String(valueOf);
            valueOf = String.valueOf(str);
            str2 = String.valueOf("last_updated");
            this.zzlr = str2.length() != 0 ? valueOf.concat(str2) : new String(valueOf);
            valueOf = String.valueOf(str);
            str2 = String.valueOf("is_in_circles");
            this.zzls = str2.length() != 0 ? valueOf.concat(str2) : new String(valueOf);
            valueOf = String.valueOf(str);
            str2 = String.valueOf("played_with_timestamp");
            this.zzlt = str2.length() != 0 ? valueOf.concat(str2) : new String(valueOf);
            valueOf = String.valueOf(str);
            str2 = String.valueOf("current_xp_total");
            this.zzlu = str2.length() != 0 ? valueOf.concat(str2) : new String(valueOf);
            valueOf = String.valueOf(str);
            str2 = String.valueOf("current_level");
            this.zzlv = str2.length() != 0 ? valueOf.concat(str2) : new String(valueOf);
            valueOf = String.valueOf(str);
            str2 = String.valueOf("current_level_min_xp");
            this.zzlw = str2.length() != 0 ? valueOf.concat(str2) : new String(valueOf);
            valueOf = String.valueOf(str);
            str2 = String.valueOf("current_level_max_xp");
            this.zzlx = str2.length() != 0 ? valueOf.concat(str2) : new String(valueOf);
            valueOf = String.valueOf(str);
            str2 = String.valueOf("next_level");
            this.zzly = str2.length() != 0 ? valueOf.concat(str2) : new String(valueOf);
            valueOf = String.valueOf(str);
            str2 = String.valueOf("next_level_max_xp");
            this.zzlz = str2.length() != 0 ? valueOf.concat(str2) : new String(valueOf);
            valueOf = String.valueOf(str);
            str2 = String.valueOf("last_level_up_timestamp");
            this.zzma = str2.length() != 0 ? valueOf.concat(str2) : new String(valueOf);
            valueOf = String.valueOf(str);
            str2 = String.valueOf("player_title");
            this.zzcc = str2.length() != 0 ? valueOf.concat(str2) : new String(valueOf);
            valueOf = String.valueOf(str);
            str2 = String.valueOf("has_all_public_acls");
            this.zzmb = str2.length() != 0 ? valueOf.concat(str2) : new String(valueOf);
            valueOf = String.valueOf(str);
            str2 = String.valueOf("is_profile_visible");
            this.zzmc = str2.length() != 0 ? valueOf.concat(str2) : new String(valueOf);
            valueOf = String.valueOf(str);
            str2 = String.valueOf("most_recent_external_game_id");
            this.zzmd = str2.length() != 0 ? valueOf.concat(str2) : new String(valueOf);
            valueOf = String.valueOf(str);
            str2 = String.valueOf("most_recent_game_name");
            this.zzme = str2.length() != 0 ? valueOf.concat(str2) : new String(valueOf);
            valueOf = String.valueOf(str);
            str2 = String.valueOf("most_recent_activity_timestamp");
            this.zzmf = str2.length() != 0 ? valueOf.concat(str2) : new String(valueOf);
            valueOf = String.valueOf(str);
            str2 = String.valueOf("most_recent_game_icon_uri");
            this.zzmg = str2.length() != 0 ? valueOf.concat(str2) : new String(valueOf);
            valueOf = String.valueOf(str);
            str2 = String.valueOf("most_recent_game_hi_res_uri");
            this.zzmh = str2.length() != 0 ? valueOf.concat(str2) : new String(valueOf);
            valueOf = String.valueOf(str);
            str2 = String.valueOf("most_recent_game_featured_uri");
            this.zzmi = str2.length() != 0 ? valueOf.concat(str2) : new String(valueOf);
            valueOf = String.valueOf(str);
            str2 = String.valueOf("has_debug_access");
            this.zzmj = str2.length() != 0 ? valueOf.concat(str2) : new String(valueOf);
            valueOf = String.valueOf(str);
            str2 = String.valueOf("gamer_tag");
            this.zzch = str2.length() != 0 ? valueOf.concat(str2) : new String(valueOf);
            valueOf = String.valueOf(str);
            str2 = String.valueOf("real_name");
            this.name = str2.length() != 0 ? valueOf.concat(str2) : new String(valueOf);
            valueOf = String.valueOf(str);
            str2 = String.valueOf("banner_image_landscape_uri");
            this.zzmk = str2.length() != 0 ? valueOf.concat(str2) : new String(valueOf);
            valueOf = String.valueOf(str);
            str2 = String.valueOf("banner_image_landscape_url");
            this.zzml = str2.length() != 0 ? valueOf.concat(str2) : new String(valueOf);
            valueOf = String.valueOf(str);
            str2 = String.valueOf("banner_image_portrait_uri");
            this.zzmm = str2.length() != 0 ? valueOf.concat(str2) : new String(valueOf);
            valueOf = String.valueOf(str);
            str2 = String.valueOf("banner_image_portrait_url");
            this.zzmn = str2.length() != 0 ? valueOf.concat(str2) : new String(valueOf);
            valueOf = String.valueOf(str);
            str2 = String.valueOf("gamer_friend_status");
            this.zzmo = str2.length() != 0 ? valueOf.concat(str2) : new String(valueOf);
            valueOf = String.valueOf(str);
            str2 = String.valueOf("gamer_friend_update_timestamp");
            this.zzmp = str2.length() != 0 ? valueOf.concat(str2) : new String(valueOf);
            valueOf = String.valueOf(str);
            str2 = String.valueOf("is_muted");
            str2 = str2.length() != 0 ? valueOf.concat(str2) : new String(valueOf);
        }
        this.zzmq = str2;
    }
}
